
spring:
  profiles:
    active: dev
  lifecycle:
    timeout-per-shutdown-phase: 10s #设置缓冲器 最大等待时间

mybatis-plus:
    mapper-locations: classpath*:/mapper/**/*.xml
    configuration:
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# 防止XSS攻击
xss:
  # 过滤开关
  enabled: true
  # 排除链接（多个用逗号分隔）
  excludes: /system/notice/*
  # 匹配链接
  urlPatterns: /system/*,/monitor/*,/tool/*






