


spring:
  profiles:
    active: dev
  lifecycle:
    timeout-per-shutdown-phase: 10s #设置缓冲器 最大等待时间

mybatis-plus:
    mapper-locations: classpath*:/mapper/**/*.xml
    configuration:
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl






