

spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/shell?useUnicode=true&useSSL=false&characterEncoding=utf8
    username: root
    password: root@123456
  main:
    allow-bean-definition-overriding: true
  jackson:
      default-property-inclusion: non_null

knife4j:
  production: true #true则屏蔽swagger资源

jwt:
  tokenHeader: Authorization #JWT存储的请求头
  secret: shell-admin-secret #JWT加解密使用的密钥
  expiration: 604800 #JWT的超期限时间(60*60*24*7)
  tokenHead: 'Bearer '  #JWT负载中拿到开头

security:
  ignoreUrl: /test/**,/swagger-resources/**




