
server:
  port: 9091
  shutdown: immediate #开启优雅停机 GRACEFUL

spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/shell?useUnicode=true&useSSL=false&characterEncoding=utf8
    username: root
    password: root@123456
  main:
    allow-bean-definition-overriding: true
  jackson:
      default-property-inclusion: non_null
  devtools:
    restart:
      enabled: true
  freemarker:
    cache: false #页面不加载缓存，修改即时生效

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


knife4j:
  production: false #true则屏蔽swagger资源

jwt:
  tokenHeader: Authorization #JWT存储的请求头
  secret: shell-admin-secret #JWT加解密使用的密钥
  expiration: 604800 #JWT的超期限时间(60*60*24*7)
  tokenHead: 'Bearer '  #JWT负载中拿到开头

security:
  ignoreUrl: /test/**,/swagger-resources/**,/user/**

task:
  pool:
    # 核心线程池大小
    core-pool-size: 2
    # 最大线程数
    max-pool-size: 4
    # 活跃时间
    keep-alive-seconds: 10
    # 队列容量
    queue-capacity: 50

rest:
  connection:
    timeout: 20000
  read:
      timeout: 5000


#日志配置 无特殊需求无需更改
logging:
  config: classpath:log4j2.xml
  level:
    root: INFO
#    javax.activation: info
#    org.apache.catalina: INFO
#    org.apache.commons.beanutils.converters: INFO
#    org.apache.coyote.http11.Http11Processor: INFO
#    org.apache.http: INFO
#    org.apache.tomcat: INFO
#    org.springframework: INFO
#    com.chinamobile.cmss.bdpaas.resource.monitor: DEBUG

