
server:
  port: 9099
  shutdown: immediate #开启优雅停机 GRACEFUL

spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/shell?useUnicode=true&useSSL=false&characterEncoding=utf8
    username: root
    password: root@123456
  main:
    allow-bean-definition-overriding: true
  jackson:
      default-property-inclusion: non_null
      time-zone: GMT+8
  redis:
    database: 0
    host: 127.0.0.1
    password:
    port: 6379
    timeout: 6000
  cache:
    type: redis

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  global-config:
    db-config:
      logic-delete-field: deleteFlag
      logic-delete-value: 1
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


aj:
  captcha:
    aes-status: true   #aes加密坐标开启或者禁用(true|false)
    cache-type: redis #缓存local/redis... # 对于分布式部署的应用，我们建议应用自己实现CaptchaCacheService，比如用Redis或者memcache，参考CaptchaCacheServiceRedisImpl.java
      # 如果应用是单点的，也没有使用redis，那默认使用内存。
    # 内存缓存只适合单节点部署的应用，否则验证码生产与验证在节点之间信息不同步，导致失败。
    # ！！！ 注意啦，如果应用有使用spring-boot-starter-data-redis，请打开CaptchaCacheServiceRedisImpl.java注释。
    cache-number: 1000 #local缓存的阈值,达到这个值，清除缓存
    timing-clear: 180  #local定时清除过期缓存(单位秒),设置为0代表不执行
    font-type: \u5b8b\u4f53
    interference-options: 2   #滑动干扰项(0/1/2) 1.2.2版本新增
#    jigsaw: classpath:images/jigsaw  #滑动验证，底图路径，不配置将使用默认图片
#    pic-click: classpath:images/pic-click #点击验证，底图路径，不配置将使用默认图片
    slip-offset: 5  #校验滑动拼图允许误差偏移量(默认5像素)
    type: default #验证码类型default两种都实例化  blockPuzzle 滑块拼图   clickWord 文字点选
    water-font: \u5b8b\u4f53 # 宋体
    water-mark: shell  #汉字统一使用Unicode,保证程序通过@value读取到是中文，可通过这个在线转换 https://tool.chinaz.com/tools/unicode.aspx 中文转Unicode

login:
  isSingle: false
  needCode: false
  enableCache: true
  publicKey: 040471008F95FFD0E1F8AD1CC886E09402F45CC8A935DAE145B88B3768C80BF6E18879AAE458FEFBBB7114F6D9F11192860359FA50B403293F00592A6061B59F8F
  privateKey: 3A2C8E1BB7B922FC7CB8E32FE7EFB6C1F3C0BF3ABAFE5560552BF67DA55BFD4B
  user:
    admin: 'ums:admin'
    expire: 86400 # 24小时
  mode: demo



knife4j:
  production: false #true则屏蔽swagger资源

jwt:
  tokenHeader: Authorization #JWT存储的请求头
  secret: shell-admin-secret #JWT加解密使用的密钥
  expiration: 604800 #JWT的超期限时间(60*30)
  tokenHead: 'Bearer '  #JWT负载中拿到开头
  refresh: 900 #15分钟内可续期

security:
  ignoreUrl: /test/**,/ums/user/**,/code

async:
  task:
    pool:
      # 核心线程池大小
      core-pool-size: 2
      # 最大线程数
      max-pool-size: 4
      # 活跃时间
      keep-alive-seconds: 10
      # 队列容量
      queue-capacity: 50

rest:
  connection:
    timeout: 20000
  read:
      timeout: 5000

justauth:
  enabled: true
  type:
    GITEE:
      client-id: 5e06fa3a0e0d3a864fd1c9d2d19df7551dbcdc04e130c2b45d24e6d8ab25f97e
      client-secret: dca4fa85200cb0ce7bc5ffb0c933e3e52da334781d4f42fdbbc9a31edd3b6b92
      redirect-uri: http://127.0.0.1:9099/oauth/gitee/callback
    GITHUB:
      client-id: bd5869573540c0122dab
      client-secret: c00cde39860c48036afccbcfaecf5ba64194f263
      redirect-uri: http://127.0.0.1:9099/test/oauth/github/callback

#日志配置 无特殊需求无需更改
logging:
  config: classpath:log4j2.xml
  level:
    root: info
#    javax.activation: info
#    org.apache.catalina: INFO
#    org.apache.commons.beanutils.converters: INFO
#    org.apache.coyote.http11.Http11Processor: INFO
#    org.apache.http: INFO
#    org.apache.tomcat: INFO
#    org.springframework: INFO
#    com.chinamobile.cmss.bdpaas.resource.monitor: DEBUG

